rtdetr:
    onnx_file:     "../weights/rtdetr/rtdetr_r50vd_6x_coco.onnx"
    engine_file:   "../weights/rtdetr/rtdetr_r50vd.trt"
    type:          "coco80"
    mode:          "fp32"
    batchSize:     1
    inputChannel:  3
    imageWidth:    640
    imageHeight:   640
    obj_threshold: 0.25
    nms_threshold: 0.45
    strides:       [8, 16, 32]
    imgMean:       [ 0, 0, 0 ]
    imgStd:        [ 1, 1, 1 ]
