yolov5:
    onnx_file:     "../weights/yolov5s.onnx"
    engine_file:   "../weights/yolov5s.trt"
    type:          "coco80"
    mode:          "fp32"
    batchSize:    1
    inputChannel: 3
    imageWidth:   640
    imageHeight:  640
    obj_threshold: 0.4
    nms_threshold: 0.45
    strides:       [8, 16, 32]
    imgMean:      [ 0, 0, 0 ]
    imgStd:       [ 1, 1, 1 ]
