yolox:
    onnx_file:     "../weights/yolox/yoloxs.onnx"
    engine_file:   "../weights/yolox/yoloxs.trt"
    type:          "coco"
    mode:          "fp32"
    dynamic:       1
    batchSize:     1
    imageWidth:    640
    imageHeight:   640
    conf_thr:      0.25
    nms_thr:       0.45
    strides:       [8, 16, 32]
    imgScale:      1
    imgMean:       [ 0, 0, 0 ]
    imgStd:        [ 1, 1, 1 ]    
